# Generated by Django 5.0.3 on 2024-08-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_trainer_master_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer_master',
            name='bank_name',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='trainer_master',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
        migrations.AddField(
            model_name='trainer_master',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
