# Generated by Django 5.0.3 on 2024-08-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_login_created_by_login_deleted_login_dev_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_request',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Completed', 'Completed')], default='Pending', max_length=255, null=True),
        ),
    ]
