# Generated by Django 5.0.3 on 2024-08-29 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_student_request_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='trainers_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_question_solved', models.IntegerField(blank=True, default=0, null=True)),
                ('comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('activities_done', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('student_feedback', models.CharField(blank=True, max_length=255, null=True)),
                ('infrastructure_feedback', models.CharField(blank=True, max_length=255, null=True)),
                ('dtm_created', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.IntegerField(blank=True, default=0, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('dtm_modified', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, max_length=1000, null=True)),
                ('dev_remarks', models.TextField(blank=True, max_length=1000, null=True)),
                ('course_schedule_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.course_schedule')),
            ],
        ),
    ]
