# Generated by Django 5.0.3 on 2024-08-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_tests_candidates_map_is_camera_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer_master',
            old_name='preferred_city',
            new_name='state',
        ),
        migrations.AddField(
            model_name='trainer_master',
            name='experience',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='trainer_master',
            name='city',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
