# Generated by Django 5.0.3 on 2024-08-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_master',
            name='is_database',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
