# Generated by Django 5.0.3 on 2024-08-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_question_master_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer_master',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
        migrations.AddField(
            model_name='trainer_master',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
