# Generated by Django 5.0.3 on 2024-07-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_candidate_master_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_master',
            name='need_candidate_info',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
