# Generated by Django 5.0.3 on 2024-07-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_candidate_master_need_candidate_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_master',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_master',
            name='core_of_offers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_master',
            name='history_of_arrears',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_master',
            name='it_of_offers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_master',
            name='marks_10th',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_master',
            name='marks_12th',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_master',
            name='number_of_offers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_master',
            name='standing_arrears',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
