# Generated by Django 5.0.3 on 2024-08-07 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_candidate_master_is_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_master',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_master',
            name='year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='eligible_student_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.TextField(blank=True, max_length=10000, null=True)),
                ('round_of_interview', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp_text', models.TextField(blank=True, max_length=10000, null=True)),
                ('deleted', models.IntegerField(blank=True, default=0, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('dtm_created', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('dtm_modified', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, max_length=1000, null=True)),
                ('dev_remarks', models.TextField(blank=True, max_length=1000, null=True)),
                ('job_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.job_master')),
                ('students_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.candidate_master')),
            ],
        ),
    ]
