# Generated by Django 5.0.3 on 2024-08-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_content_detail_content_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligible_student_list',
            name='is_accept',
            field=models.BooleanField(default=False),
        ),
    ]
