# Generated by Django 5.0.3 on 2024-08-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_trainer_master_bank_name_trainer_master_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_master',
            name='dtm_upload',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
