# Generated by Django 5.0.3 on 2024-08-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_student_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_request',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
