# Generated by Django 5.0.3 on 2024-08-23 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_preferred_city_trainer_master_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshots', models.BinaryField(blank=True, null=True)),
                ('dtm_created', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.IntegerField(blank=True, default=0, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('dtm_modified', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, max_length=1000, null=True)),
                ('dev_remarks', models.TextField(blank=True, max_length=1000, null=True)),
                ('test_candidate_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tests_candidates_map')),
            ],
        ),
    ]
