# Generated by Django 5.0.3 on 2024-08-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_eligible_student_list_is_offered_job_master_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='deleted',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='dev_remarks',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='dtm_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='dtm_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='dtm_trainer',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='modified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='remarks',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
