# Generated by Django 5.0.3 on 2024-08-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_trainers_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer_master',
            name='is_edit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trainer_master',
            name='is_terms',
            field=models.BooleanField(default=False),
        ),
    ]
