# Generated by Django 5.0.3 on 2024-08-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_address_trainer_master_gst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligible_student_list',
            name='is_offered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job_master',
            name='job_type',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
