"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""


import os
from pathlib import Path


# Define BASE_DIR to be the root of your Django project
BASE_DIR = Path(__file__).resolve().parent.parent

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'debug.log'),
            'formatter': 'verbose',
        },
        'console': {
            'level': 'ERROR',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',  # Set root logger to WARNING
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'WARNING',  # Log only warnings and errors for Django
            'propagate': False,
        },
        'app': {
            'handlers': ['file', 'console'],
            'level': 'ERROR',  # Detailed logging for your app
            'propagate': False,
        },
        # Add other specific loggers here as needed
    },
}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-sa3j@%j2sa*cnb+-so1&=nv2q20r2skr$*%)-qz2v!aaqd$6a_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'app', 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware', 
    'silk.middleware.SilkyMiddleware', 
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'cc_db6',
        'USER':'cc_dev',
        'PASSWORD':'CA!mp2us3',
        # 'NAME': 'ccportal',
        # 'USER': 'postgres',
        # 'PASSWORD': 'xszZcLqrdSzM06KnuyI0',
        # 'HOST': 'cc-portal.cv0aoio6ihof.ap-south-1.rds.amazonaws.com',
        # 'HOST': '66.23.230.20'
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'static')
]
ASSET_DIR = os.path.join(BASE_DIR, 'assets')

CODE_EXECUTION_TIMEOUT=60

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ORIGIN_WHITELIST = [
     'http://localhost:3000',
     'http://66.23.230.20:3000',
     #'https://cc.kwantumg.com',
     'https://ccportal.co.in',
     'cc-portal.cv0aoio6ihof.ap-south-1.rds.amazonaws.com'

]


CORS_ALLOW_CREDENTIALS = True
SESSION_COOKIE_SAME_SITE = None
SESSION_COOKIE_SECURE = False
CORS_ALLOW_ALL_ORIGINS = True
SESSION_COOKIE_HTTPONLY = False



CORS_ALLOWED_ORIGINS = [
    'http://127:0:0:1:5173',
    'http://localhost:5173',
    'http://localhost:3000',
    'http://54.227.21.199:8000',
    'http://43.231.127.246:8000',
    'http://43.231.127.246:3000',
    'http://66.23.230.20:8000',
    'http://66.23.230.20:3000',
    'http://cc-portal.cv0aoio6ihof.ap-south-1.rds.amazonaws.com:8000',
    'http://cc-portal.cv0aoio6ihof.ap-south-1.rds.amazonaws.com:3000'
   
]

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    '54.227.21.199',
    '43.231.127.246:3000',
    '43.231.127.246',
    '66.23.230.20:3000',
    '66.23.230.20',
    'cc.kwantumg.com',
    'ccportal.co.in',
    'cc-portal.cv0aoio6ihof.ap-south-1.rds.amazonaws.com:3000',
    'cc-portal.cv0aoio6ihof.ap-south-1.rds.amazonaws.com'
]

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]



# Add this to ensure CSRF token is set in cookies
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_SAME_SITE = None
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_HTTPONLY = False


