# Generated by Django 5.0.3 on 2024-08-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_is_actual_test_tests_candidates_map_is_camera_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests_candidates_map',
            name='is_camera_on',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
