# Generated by Django 5.0.3 on 2024-08-17 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_candidate_master_dtm_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tests_candidates_map',
            old_name='is_actual_test',
            new_name='is_camera_on',
        ),
    ]
