# Generated by Django 5.0.3 on 2024-08-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_job_master_interview_date_job_master_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement_master',
            name='announcement',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='announcement_master',
            name='announcement_image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eligible_student_list',
            name='announcement_image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
