# Generated by Django 5.0.3 on 2024-08-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_create_procedure_in_question_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_master',
            name='deleted',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
    ]
